### PR TITLE
Fix leaking context in callbacks/listeners

### LINKED ISSUE #108: Automatically clearing callbacks
**Describe the bug**
Library allows to pass a callback that will be invoked when a button in Cockpit menu is clicked. It's easy to create a memory leak with the current implementation.

**Library version**
Version of Cockpit the issue occurs in: `3.0.1`.

**To reproduce**
Add a callback:
```
// we're inside Activity's onCreate
Cockpit.addFooCallback {
    // access Activity methods or fields 
}
```
Such callback captures activity instance and is kept by Cockpit. If we rotate the device then we have a memory leak.
To avoid that we can do:
```
val fooCallback = ActionRequestCallback {
    // access Activity methods or fields 
}

// in onCreate
Cockpit.addFooCallback(fooCallback)

// in onDestroy
Cockpit.removeFooCallback(fooCallback)
```
Maybe it would be possible to automatically remove the callbacks when necessary? Or at least add a possibility to enable/disable automatic callback removal? I'm not 100% sure that we want to always remove them, it's a topic for discussion. Just wanted to leave it here.

### PR DESCRIPTION
**Pull request by mikolak**
Fixes #108

### CODE REVIEW

File: CockpitPlugin/src/main/java/com/polidea/cockpitplugin/generator/DebugCockpitGenerator.kt [hunk 1]
```diff
@@ -209,13 +275,38 @@ internal class DebugCockpitGenerator : BaseCockpitGenerator() {
...
 
-    private fun createAddPropertyChangeListenerMethodSpecForWrappableParam(paramName: String, paramClass: Class<*>, mapperName: String, listenerMapName: String, wrappableClassName: TypeName): MethodSpec {
+    private fun createAddPropertyChangeListenerMethodSpecForWrappableParam(
+            paramName: String,
+            paramClass: Class<*>,
+            mapperName: String,
+            listenerMapName: String,
+            wrappableClassName: TypeName,
+            deprecated: Boolean = false,
+            takeLifecycleOwner: Boolean = false): MethodSpec { // TODO gdzie teraz jest twój bóg?
```
Comment (mzgreen) [inline CockpitPlugin/src/main/java/com/polidea/cockpitplugin/generator/DebugCockpitGenerator.kt]: What is this comment about? 😉

Comment (martawoldanska) [reply CockpitPlugin/src/main/java/com/polidea/cockpitplugin/generator/DebugCockpitGenerator.kt]: @mikolak 😱

File: cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt [hunk 2]
```diff
@@ -1,27 +1,53 @@
...
     }
 
-    private fun getCallbacks(name: String): MutableSet<ActionRequestCallback> = callbacks[name] ?: mutableSetOf()
+    private fun getCallbacks(name: String): MutableSet<LifecycleAwareCallback> = callbacks[name] ?: mutableSetOf()
+}
+
+private class LifecycleAwareCallback(val lifecycleOwner: LifecycleOwner?,
+                                     val callback: ActionRequestCallback,
+                                     val paramName: String,
+                                     val notifier: CallbackNotifier) : LifecycleObserver {
```
Comment (mzgreen) [inline cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt]: I think you could put whole `LifecycleAwareCallback` class inside `CallbackNotifier` and that would allow `LifecycleAwareCallback` class to access `callbacks` map directly. Without passing `CallbackNotifier` instance to every `LifecycleAwareCallback`.

File: cockpit/src/main/java/com/polidea/cockpit/manager/ParamChangeNotifier.kt [hunk 3]
```diff
@@ -1,31 +1,57 @@
...
     }
 
     private inline fun <reified T : Any> getListeners(name: String): T =
             (listeners[name] ?: mutableSetOf<T>()).let { it as T }
+}
+
+private class LifecycleAwareListener<T : Any>(val lifecycleOwner: LifecycleOwner?,
+                                              val listener: PropertyChangeListener<T>,
+                                              val paramName: String,
+                                              val notifier: ParamChangeNotifier) : LifecycleObserver {
```
Comment (mzgreen) [inline cockpit/src/main/java/com/polidea/cockpit/manager/ParamChangeNotifier.kt]: Same as with `LifecycleAwareCallback` above.

File: cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt [hunk 4]
```diff
@@ -1,27 +1,53 @@
...
+    init {
+        lifecycleOwner?.lifecycle?.addObserver(this)
+    }
+
+    @OnLifecycleEvent(Lifecycle.Event.ON_DESTROY)
```
Comment (mzgreen) [inline cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt]: I don't see it anywhere but I believe that to make those annotations work you need to add `androidx.lifecycle:lifecycle-compiler` dependency.

File: CockpitPlugin/src/main/java/com/polidea/cockpitplugin/generator/DebugCockpitGenerator.kt (hunk 1 above)
Comment (mikolak) [reply CockpitPlugin/src/main/java/com/polidea/cockpitplugin/generator/DebugCockpitGenerator.kt]: Got stuck yesterday and left myself a note, sorry!

File: cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt (hunk 4 above)
Comment (mikolak) [reply cockpit/src/main/java/com/polidea/cockpit/manager/CallbackNotifier.kt]: They work as is, I've checked it before creating PR.
